[package]
name = "pbgui-withs"
version = "0.18.0"
authors = ["jgerber <jlgerber@gmail.com>"]
edition = "2018"

[dependencies]
qt_core = "0.4.1"
qt_gui = "0.4.1"
qt_widgets = "0.4.1"
qt_ui_tools = "0.4.1"
log = "0.4.8"
rustqt-utils = {git = "https://github.com/jlgerber/rustqt-utils", tag="v0.6.0"}
