[package]
name = "pbgui"
version = "0.3.0"
authors = ["jgerber <jlgerber@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packybara = {git= "https://github.com/jlgerber/packybara", tag="v0.16.0"}
qt_core = "0.4.0"
qt_gui = "0.4.0"
qt_widgets = "0.4.0"
qt_ui_tools = "0.4.0"