[package]
name = "pbgui"
version = "0.7.0"
authors = ["jgerber <jlgerber@gmail.com>"]
edition = "2018"

[dependencies]
packybara = {git= "https://github.com/jlgerber/packybara", tag="v0.20.0"}
qt_core = "0.4.0"
qt_gui = "0.4.0"
qt_widgets = "0.4.0"
qt_ui_tools = "0.4.0"
whoami = "0.6.0"
